# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc13441a72f00efd55e38417fb2f170a33b84e4d088b204d197874f3e8ad4d7d24f8ea398e1930da6e70feafc1d89e91f98592b0b1e08a5767ad5332f837b297

test:
  secret_key_base: 6616fa8347ec59709d966b0284cd6d617c66c5b4823810046c9de88676124ba374891595e47c9d773112e9183fff563af3f5b0d797e9a7dc3b4cff9fa8a121b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
